version: "3.9"
services:
  app:
    image: "ghcr.io/remla23-team16/app:latest"
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://model-service:8080
  model-service:
    image: "ghcr.io/remla23-team16/model-service:latest"
    environment:
      - CLASSIFIER_PATH=/app/data/out/classifier/
      - BOW_PATH=/app/data/out/bow/
    volumes:
      - trained_models:/app/data/out
  model-training:
    image: "ghcr.io/remla23-team16/model-training:latest"
    volumes:
      - trained_models:/app/data/out
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    command:
      - --config.file=/etc/prometheus/prometheus-config.yml
volumes:
  trained_models: