apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-svc
  endpoints:
    - interval: 5s
      port: "3000"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-service-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: model-service-svc
  endpoints:
    - interval: 5s
      port: "8080"
