apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels: { app: app, version: v1}
spec:
  replicas: 1
  selector:
    matchLabels: { app: app, version: v1}
  template:
    metadata:
      labels: { app: app, version: v1}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: app
          image: ghcr.io/remla23-team16/app:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://model-service-svc:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels: { app: app, version: v2}
spec:
  replicas: 1
  selector:
    matchLabels: { app: app, version: v2}
  template:
    metadata:
      labels: { app: app, version: v2}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: app
          image: ghcr.io/remla23-team16/app:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://model-service-svc:8080